<?php

return [

	'ENTITY_CODE_CLIENT' => 'clnt',
	 

	'USER_PLATFORM_Android'=>0,
	'USER_PLATFORM_Ios'=>1,

	'USER_TYPE_EMPLOYEE'=>0,
	'USER_TYPE_CLIENTREP'=>1,
 

	'DEFAULT_LANG'=>'en-us',
   


	'true'=>1,
	'false'=>0,
  
	'ENUM_STATUS_NEW' => 1,
	'ENUM_STATUS_PENDING' => 2,
	'ENUM_STATUS_SUCCESS' => 3,
	'ENUM_STATUS_FAILED'=> 4,
  
	"MISSION_STATUS_DECLIENED" => -2,//
    'MISSION_STATUS_CANCELLED'=> -1,//
    'MISSION_STATUS_DRAFT'=> 0,//
	'MISSION_STATUS_REQUEST'=> 1, //
    'MISSION_STATUS_PENDING'=> 2, //
	'MISSION_STATUS_APPROVED'=> 3,//
	'MISSION_STATUS_RUNNING'=> 4,//  
	'MISSION_STATUS_COMPLETED'=> 6,//

  

	
	
	'_CLIENTS_FIREBASE_TOPIC' => 'CLIENTS_TOPIC',
	'_EMPLOYEE_FIREBASE_TOPIC' => '_EMPLOYEE_TOPIC',
];

